import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import importPlugin from "eslint-plugin-import";
import sonarjs from "eslint-plugin-sonarjs";
import tseslint from "typescript-eslint";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    plugins: { import: importPlugin, sonarjs },
    rules: {
      // CLAUDE.md: "TypeScript strict, `any` yok"
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-non-null-assertion": "off",
      eqeqeq: ["error", "always"],
      curly: ["error", "all"],
      "no-console": ["warn", { allow: ["warn", "error"] }],

      // Import sıralama/organizasyon
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal", ["parent", "sibling", "index"]],
          pathGroups: [{ pattern: "@/**", group: "internal" }],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "import/no-duplicates": ["error", { "prefer-inline": true }],
      "import/newline-after-import": "error",
      "import/no-self-import": "error",

      // Sadeleştirme/güzelleştirme
      "object-shorthand": "error",
      "prefer-template": "error",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-lonely-if": "error",
      "no-nested-ternary": "error",
      "no-unneeded-ternary": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "error",
      "no-useless-computed-key": "error",
      "prefer-arrow-callback": "error",

      // Kod tekrarını önleme (CLAUDE.md: "asla kod tekrarı yapma")
      "sonarjs/no-identical-functions": "error",
      "sonarjs/no-duplicated-branches": "error",
      "sonarjs/no-all-duplicated-branches": "error",
      "sonarjs/no-identical-expressions": "error",
    },
  },
  {
    // Component'leri küçük tutma kuralı (CLAUDE.md). Mantık custom hook'a
    // taşınmalı — büyüyen bir component fonksiyonu genelde bunun ihlal
    // edildiğinin işareti.
    files: ["src/app/**/*.tsx", "src/components/**/*.tsx"],
    ignores: ["src/components/ui/**"],
    rules: {
      "max-lines-per-function": [
        "warn",
        { max: 100, skipBlankLines: true, skipComments: true },
      ],
    },
  },
  {
    // Ham <input>/<button> yerine primitive kullanımını zorla (CLAUDE.md:
    // "primitive UI bileşenlerine önem ver"). shadcn primitives'in kendisi
    // (src/components/ui) muaf, çünkü ham elementleri onlar sarmalıyor.
    files: ["src/app/**/*.tsx", "src/components/**/*.tsx"],
    ignores: ["src/components/ui/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "JSXOpeningElement[name.name='button']",
          message: "Ham <button> yerine @/components/ui/button kullan.",
        },
        {
          selector: "JSXOpeningElement[name.name='input']",
          message: "Ham <input> yerine @/components/ui/input kullan.",
        },
      ],
    },
  },
  {
    // Plain JS config files aren't part of tsconfig.json's `include`, so they
    // can't be type-checked by the project service — lint them untyped instead.
    // Must come after the strict rule overrides above so it wins for these files.
    files: ["*.config.mjs"],
    extends: [tseslint.configs.disableTypeChecked],
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase gen types` — not hand-written, don't lint it.
    "src/types/database.types.ts",
    // Generated by `npx shadcn add chart` — vendored recharts wrapper, not
    // hand-written; upstream code doesn't conform to our strict any/type rules.
    "src/components/ui/chart.tsx",
  ]),
]);

export default eslintConfig;
